### ISSUE TITLE
VSTS-TASK-LIB renaming to azure-pipelines-task-lib error

### ISSUE THREAD

**Issue by knom** [Microsoft/azure-pipelines-task-lib#464]
When I download the latest version from NPM (azure-pipelines-task-lib - 2.7.0) there is an error!

In `node_modules\azure-pipelines-task-lib\mock-run.js` line number 63 it says:
`var tlm = require('vsts-task-lib/mock-task');`

Obviously it cannot find vsts-task-lib..

Did you miss that in your find/replace?

It clearly has changed on GitHub - but not on NPM?

Here's the stacktrace...

```
STDERR: module.js:549
    throw err;
    ^

Error: Cannot find module 'vsts-task-lib/mock-task'
    at Function.Module._resolveFilename (module.js:547:15)
    at Module._load (module.js:474:25)
    at Function.hookedLoader [as _load] (C:\Work\TFS\vsts-markdown-tasks\node_modules\mockery\mockery.js:111:12)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at TaskMockRunner.run (C:\Work\TFS\vsts-markdown-tasks\node_modules\azure-pipelines-task-lib\mock-run.js:63:23)
    at Object.<anonymous> (C:\Work\TFS\vsts-markdown-tasks\test\MultiFiles_Mock.js:23:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

Thanks!

**Comment by damccorm** [comment]
@bryanmacfarlane I think this was fixed here: https://github.com/Microsoft/azure-pipelines-task-lib/pull/457/commits/c2b2d2ceb991d57796f803c01e3a19a0a722361d it just hasn't been published to npm. Can you publish 2.7.1?

**Comment by bryanmacfarlane** [comment]
Done.  2.7.1 published
