### ISSUE TITLE
Azure pipeline extension task test failed with Error: connect ETIMEDOUT <IP>:443

### ISSUE THREAD

**Issue by ganesh-kashid** [microsoft/azure-pipelines-task-lib#690]
### Environment
azure-pipelines-task-lib version:  azure-pipelines-task-lib@3.0.6-preview.0

### Issue Description
I am trying to create a Azure pipeline extension task by referring https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops. I am facing below issue post executing "mocha tests/_suite.js". Any help would be greatly appreciated. As soon as works I need to work on a custom task that will be required in TFS 2017 release pipeline.

Sample task tests
Downloading file: https://nodejs.org/dist/v10.21.0/win-x64/node.exe
1) should succeed with simple inputs
Downloading file: https://nodejs.org/dist/v10.21.0/win-x64/node.exe
2) it should fail if tool returns 1

0 passing (2m)
2 failing

1) Sample task tests
should succeed with simple inputs:
Error: connect ETIMEDOUT <IP>:443
at extractValue (node_modules\sync-rpc\lib\index.js:165:19)
at \node_modules\sync-rpc\lib\index.js:175:12
at Function.request [as default] (node_modules\sync-request\lib\index.js:28:15)
at MockTestRunner.downloadFile (node_modules\azure-pipelines-task-lib\mock-test.js:240:44)
at MockTestRunner.downloadNode (node_modules\azure-pipelines-task-lib\mock-test.js:220:22)
at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:151:25)
at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:29:30)

### Expected behaviour
Both tests should be passed

### Actual behaviour
An error occurred as described in description section

### Steps to reproduce
Refer steps in https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops

**Comment by babu2082** [comment]
Does this issue has been addressed, am also into the same scenario.
