### ISSUE TITLE
Error running tests with VS Code

### ISSUE THREAD

**Issue by trevren11** [microsoft/azure-pipelines-task-lib#699]
### Environment
azure-pipelines-task-lib version: 3.0.6-preview.1

### Issue Description
Following the guide [here](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops&viewFallbackFrom=vsts) I get the task setup, then go to run the tests with VS code debug. When it tries to read the json, it reads an extra character (byte value of 65279) even after the file is fully converted to utf-8. Adding trim fixes behavior and resolves the error below 

![image](https://user-images.githubusercontent.com/8571163/106936580-9ccfe380-66d1-11eb-8bb2-77bbcd099781.png)

### Expected behaviour
Tests should pass

### Actual behaviour
Tests can't run due to the SyntaxError Unexpected <?> token in json at position 0

### Steps to reproduce
1. Follow https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops&viewFallbackFrom=vsts
2. Set up VS code debug session
3. Try to run tests (`tsc; mocha .\tests\_suite.js`)
4. Get failure message, tests don't run successfully 

### Logs
```
PS C:\...\buildAndReleaseTask> tsc; mocha .\tests\_suite.js


  Sample task tests
    1) should succeed with simple inputs
    2) it should fail if tool returns 1


  0 passing (23ms)
  2 failing

  1) Sample task tests
       should succeed with simple inputs:
     SyntaxError: Unexpected token ﻿ in JSON at position 0
      at JSON.parse (<anonymous>)
      at MockTestRunner.getNodeVersion (node_modules\azure-pipelines-task-lib\mock-test.js:162:29)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:126:43)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:29:30)
      at Context.<anonymous> (tests\_suite.js:37:18)
      at processImmediate (internal/timers.js:461:21)

  2) Sample task tests
       it should fail if tool returns 1:
     SyntaxError: Unexpected token ﻿ in JSON at position 0
      at JSON.parse (<anonymous>)
      at MockTestRunner.getNodeVersion (node_modules\azure-pipelines-task-lib\mock-test.js:162:29)
      at MockTestRunner.getNodePath (node_modules\azure-pipelines-task-lib\mock-test.js:126:43)
      at new MockTestRunner (node_modules\azure-pipelines-task-lib\mock-test.js:29:30)
      at Context.<anonymous> (tests\_suite.js:50:18)
      at processImmediate (internal/timers.js:461:21)


```

**Comment by DaniilShmelev** [comment]
Hi @trevren11! I see that you closed your PR because your problem has resolved on it's own.
Should this issue be closed, or are there any steps still needed from our side?
